services:

    feed.manager:
        class: FeedBundle\Utils\FeedEntityManager
        arguments: ["@doctrine.orm.entity_manager"]
        autowire: true

    feed.handler:
        class: FeedBundle\Handler\FeedHandler
        arguments: ["@feedio", "@doctrine.orm.entity_manager", "%rss_feeder.limit_curl%", "@feed.manager"]