services:

    feed.manager:
        class: Gubarev\Bundle\FeedBundle\Utils\FeedEntityManager
        arguments: ["@doctrine.orm.entity_manager"]
        autowire: true

    feed.handler:
        class: Gubarev\Bundle\FeedBundle\Handler\FeedHandler
        arguments: ["@feedio", "@feed.manager", "%rss_feeder.limit_curl%"]