<?php

namespace FeedBundle\Repository;

use FeedBundle\Repository\Interfaces\RepositoryInterface;

/**
 * CategoryEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryEntityRepository extends \Doctrine\ORM\EntityRepository implements RepositoryInterface
{
    public function truncate()
    {
        return $this->getEntityManager()
            ->createQuery('DELETE FROM FeedBundle:CategoryEntity')->execute();
    }
}
