<?php

namespace ComponentBundle\Repository;

/**
 * MediaEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaEntityRepository extends \Doctrine\ORM\EntityRepository
{
    public function truncate()
    {
        return $this->getEntityManager()
            ->createQuery('DELETE FROM ComponentBundle:MediaEntity')->execute();
    }
}
