<?php

namespace Gubarev\Bundle\FeedBundle\Repository;

use Gubarev\Bundle\FeedBundle\Repository\Interfaces\RepositoryInterface;

/**
 * NewsEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsEntityRepository extends \Doctrine\ORM\EntityRepository implements RepositoryInterface
{
    public function truncate()
    {
        return $this->getEntityManager()
            ->createQuery('DELETE FROM Gubarev\Bundle\FeedBundle\Entity\NewsEntity')->execute();
    }
}
